spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: billing-server
              uri: lb://billing-server
              predicates:
                - Path=/api/**

  http:
    client:
      connect-timeout: 3000