#spring:
  #security:
    #oauth2:
     # resourceserver:
        #jwt:
          #issuer-uri: http://keycloak:8080/realms/kerp
keycloak:
  issuer-uri: ${KEYCLOAK_URL}
logging:
  level:
    org.springframework.security: WARN
    org.springframework.cloud.gateway: WARN
    root: WARN