spring:
  #security:
    #oauth2:
      #resourceserver:
        #jwt:
          #issuer-uri: http://localhost:8080/realms/kerp

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: billing-server
              uri: lb://billing-server
              predicates:
                - Path=/api/**
              filters:
                - RemoveRequestHeader=Origin
                - RemoveRequestHeader=Authorization

  http:
    client:
      connect-timeout: 3000

logging:
  level:
    org.springframework.security: DEBUG