spring:
  application:
    name: billing-server

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

  datasource:
    #  Docker  → url: jdbc:postgresql://billing-db:5432/billing_db
    #  Local   → url: jdbc:postgresql://localhost:5432/billing_db
    url: jdbc:postgresql://billing-db:5432/billing_db
    username: postgres
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    out-of-order: false

  storage:
    type: database

    local:
      root-path: ./storage
      public-base-url: http://localhost:8081

    cloud:
      provider: r2

    database:
      download-path: /api/documents/


  r2:
    account-id: ${R2_ACCOUNT_ID}
    access-key-id: ${R2_ACCESS_KEY_ID}
    secret-access-key: ${R2_SECRET_ACCESS_KEY}
    bucket-name: ${R2_BUCKET_NAME}
    public-base-url: ${R2_PUBLIC_BASE_URL:}
    region: ${R2_REGION:auto}

server:
  port: 8081