spring:
  application:
    name: billing-server
  management:
    endpoints:
      web:
        exposure:
          include: "info,health"
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 45MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
  r2:
    account-id: ${R2_ACCOUNT_ID}
    access-key-id: ${R2_ACCESS_KEY_ID}
    secret-access-key: ${R2_SECRET_ACCESS_KEY}
    bucket-name: ${R2_BUCKET_NAME}
    public-base-url: ${R2_PUBLIC_BASE_URL:}
    region: ${R2_REGION:auto}
  exchange-rate:
    api:
      base-url: https://api.exchangerate.host
      key: ${EXCHANGERATE}
  mail:
    host: smtp.gmail.com
    port: 587
    username: wassefammar17@gmail.com
    password: ${GMAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1