spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/billing_db
    username: ${DB_USER}
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  storage:
    type: database
    local:
      root-path: ./storage
      public-base-url: http://localhost:8081
    cloud:
      provider: r2
    database:
      download-path: /api/billing/documents/

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: >
          notificationEvent:com.example.billingservice.infrastructure.out.messaging.NotificationEvent,
          mailRequest:com.example.billingservice.infrastructure.out.persistance.dto.MailRequest,
          auditEvent:com.example.billingservice.infrastructure.out.messaging.AuditEvent

    consumer:
      group-id: billing-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: >
          mailResult:com.example.billingservice.infrastructure.out.persistance.dto.MailResultDTO


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    context-path: /api/billing
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG
    root: info