spring:
  application:
    name: billing-server

  management:
    endpoints:
      web:
        exposure:
          include: "info,health"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  r2:
    account-id: ${R2_ACCOUNT_ID}
    access-key-id: ${R2_ACCESS_KEY_ID}
    secret-access-key: ${R2_SECRET_ACCESS_KEY}
    bucket-name: ${R2_BUCKET_NAME}
    public-base-url: ${R2_PUBLIC_BASE_URL:}
    region: ${R2_REGION:auto}

  exchange-rate:
    api:
      base-url: https://api.exchangerate.host
      key: "e4e119ef94a7b2c5514cf314fec7cd52"

  mail:
    host: smtp.gmail.com
    port: 587
    username: wassefammar17@gmail.com
    password: ${GMAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: billing-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.billingservice.infrastructure.out.persistance.dto.MailResultDTO
        spring.json.use.type.headers: false

server:
  servlet:
    context-path: /api/billing
    multipart:
      max-file-size: 15MB
      max-request-size: 45MB
  port: 8081
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1