spring:
  datasource:
    url: jdbc:postgresql://billing-db:5432/billing_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false


  storage:
    type: database
    local:
      root-path: /app/storage
      public-base-url: ""
    cloud:
      provider: r2
    database:
      download-path: /api/billing/documents/

  kafka:
    bootstrap-servers: kafka:9092

  rabbitmq:
    host: rabbit-mq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}


logging:
  level:
    org.springframework.web: WARN
    root: WARN