spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true

  kafka:
    bootstrap-servers: localhost:29092

keycloak:
  auth-server-url: http://localhost:8080
  client-secret: TGNBK5j6PBWKP1MIXgorOcuX8KCXYPSd


logging:
  level:
    root: info
    com.KrakennTunisie.IAM_server: DEBUG

