spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: false

keycloak:
  auth-server-url: http://localhost:8080
  client-secret: dev-secret-non-sensible

logging:
  level:
    root: info
    com.KrakennTunisie.IAM_server: DEBUG

