server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/Config

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false